sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull riot/riotbuild

env:
  global:
  - BUILD_IN_DOCKER=1
  - WERROR=0

matrix:
  include:
  - name: "Build tutorials for native"
    env: BOARD=native
  - name: "Build tutorials for samr21-xpro"
    env: BOARD=samr21-xpro
  - name: "Build tutorials for phyWAVE-KW22"
    env: BOARD=pba-d-01-kw2x

before_script:
  - export J="$(( $(grep -c ^processor /proc/cpuinfo) * 2 ))"

script:
  - make -C task-01 -j${J} all
  - make -C task-02 -j${J} all
  - make -C task-03 -j${J} all
  - make -C task-04 -j${J} all
  - make -C task-05 -j${J} all
  # task-07
  - make -C RIOT/examples/gnrc_minimal -j${J} all
  - make -C RIOT/examples/gnrc_networking -j${J} all
  - make -C task-06 -j${J} all
  - make -C task-08 -j${J} all
  - make -C task-09 -j${J} all
